### ISSUE TITLE
Switch from Rework to PostCSS ?

### ISSUE THREAD

**Issue by MoOx** [segmentio/myth#100]
I'm thinking about that because I'm tired of having difficulties to do what I want with rework ecosystem.
Ref:
- https://github.com/reworkcss/css/issues/44
- https://github.com/reworkcss/rework-custom-media/issues/2
- https://github.com/reworkcss/rework-vars/issues/30
- https://github.com/reworkcss/rework-vars/issues/34

You can say I'm a maniac or something (sort of, yes) but I would like to have more control on the output, because I like when things are clean (& fast). 
Plus, right now we have 3 parsings (rework -> postcss (autoprefixer) -> rework again), so benefit would be huge.

Now that postcss is using es6 (and not coffeescript)  it should be easy to go forward with this project.

It should not be that hard to do that because we don't have a lot of work to do.
Postcss have a nicer API, is fast enough + we can already keep all existing tests on all plugins to create postcss-\* plugins (to avoid regressions). I'm hot to handle that, using a postcss org (@ai plz tell me if it's an issue for you or not)

Here is a sort of bench based on parsing on github css https://gist.github.com/MoOx/1b0d7d2bd987e0735e0e
You will see that postcss is (on avg) 40% slower.
That being said, you need to know that rework doesn't keep at all coding style (whitespace & shit) & postcss does.
For the live playground planned on myth.io website, that would be nice to keep coding styles. And for maniac too :)

Since we are (for now) parsing 2 times with rework & one time with postcss, we will win something for sure.

Not sure if it's the best idea of the week but I want to share it with the community.

**Comment by stevenvachon** [comment]
I just found out about postcss today. Yeah, late. Rework's media queries still don't work? Sounds like a dead project.

**Comment by MoOx** [comment]
FYI, I've done a myth like based on postcss, and v1.0 has just been released http://cssnext.github.io/

**Comment by stevenvachon** [comment]
Cool. Are there any drawbacks?

**Comment by MoOx** [comment]
Just more features & less bug. You can play with it online http://cssnext.github.io/cssnext-playground/

**Comment by MoOx** [comment]
Here is an outdated comparison https://gist.github.com/MoOx/091143e99c6c87fa6d13 with myth 1.1.1 vs cssnext 0.3.1

**Comment by stevenvachon** [comment]
Cool, I might just switch. But, I'm not sure if you answered my other question: what does cssnext do that postcss doesn't already? If fewer bugs, why not just contribute to postcss?

**Comment by MoOx** [comment]
Like myth uses rework, cssnext uses postcss as engine.
