### ISSUE TITLE
Meteor package

### ISSUE THREAD

**Issue by davidbourguignon** [segmentio/myth#101]
Dear Myth Team,

I discovered Myth recently and found your approach very interesting, in comparison with other CSS preprocessors. By any chance, do you intend to develop a Myth package for Meteor? I found [nothing on Atmosphere](http://atmospherejs.com/?q=myth) while there are [many things available for Stylus](http://atmospherejs.com/?q=stylus) for example. (Stylus itself has an official Meteor package.) If not, do you think it could be worth for me to give it a try? Thanks in advance for your help!

Best regards,

David.

**Comment by isaaki** [comment]
@davidbourguignon Meteor's now at 1.0.2.1, any progress on a myth package for it?

**Comment by aquator** [comment]
Hi, I found Myth yesterday, and I really like it, so here is the plugin I made for meteor.
https://github.com/aquator/meteor-myth

It's on Atmosphere as well, so you can install it as usual.
https://atmospherejs.com/aquator/myth

**Comment by stevenmiller888** [comment]
^ cc @ianstormtaylor

**Comment by ianstormtaylor** [comment]
Awesome! Feel free to PR it into the Readme!

**Comment by aquator** [comment]
PR is on the way: #118

**Comment by davidbourguignon** [comment]
@igregson My most sincere apologies for not replying earlier... I got swamped with other jobs and spent an awful lot of time away from GitHub.

@aquator Thanks a lot for delivering! I will definitely have a look.
