### ISSUE TITLE
Using with rework-npm

### ISSUE THREAD

**Issue by voronianski** [segmentio/myth#120]
I'm using myth on my project, but now I would like to add some useful utilities from [Basscss](http://www.basscss.com/). The problem is that Basscss is using [rework-npm]() in order to manage dependencies, examples: 

- https://github.com/jxnblk/basscss-color-base/blob/master/index.css#L3
- https://github.com/jxnblk/basscss-grid/blob/master/index.css#L3

Myth fails to build such files and dependencies. Any piece of advice or workaround to get this right?

**Comment by MoOx** [comment]
You might disable import of myth & use rework + rework-npm + myth (with myth as a rework plugin). Or you can try cssnext which handle deps like rework-npm ;)

**Comment by voronianski** [comment]
@MoOx thanks, cssnext works like a charm as myth replacer :+1:
