### ISSUE TITLE
box-sizing

### ISSUE THREAD

**Issue by eswak** [segmentio/myth#122]
Hi guys,

I think it would be a good idea to add prefixes to the `box-sizing` CSS rule by default. Some not-so-old browsers (like FF28) still require the `-moz-` prefix to understand it.

Caniuse link : http://caniuse.com/#search=box-sizing

I'm not sure about how to submit a pull request here, I'm just using the `gulp-myth` community plugin to prefix our CSS, and some client complained about a layout issue related to the `box-sizing` sizing with his FF24. I checked out the problem and turns out this property is not prefixed by `myth` !

**Comment by MoOx** [comment]
This is related to autoprefixer not myth.
You just need to provide the correct `browsers` option which is passed to autoprefixer https://github.com/postcss/autoprefixer#browsers
