### ISSUE TITLE
Add ignore-errors option

### ISSUE THREAD

**Issue by Danwakefield** [segmentio/myth#133]
Im generally in the habit of saving my files everytime I exit insert mode. This can cause errors when using `myth --watch`.
It would be nice to have an option to write any errors to stdout and reenter the watch loop without stopping.

Im not well versed in js but it looks like a conditional over the `process.exit(1)` call in `logger.throw` would do it.

**Comment by ianstormtaylor** [comment]
Good call! Just landed in `1.5.0`
