### ISSUE TITLE
What is to be the fate of this project?

### ISSUE THREAD

**Issue by zeke** [segmentio/myth#140]
This is a great project, but it hasn't been updated in over six months. I just heard from @ianstormtaylor that he no longer has commit access to this repo. Does anyone at Segment intend to maintain it? If not, I would be interested in helping to keep it alive, and maybe others would too.

cc @lambtron @reinpk @anthonyshort @garysoed @MoOx @joshmoore

**Comment by stephenmathieson** [comment]
hey @zeke- we do use this internally on quite a few projects.  that said, if no one you pinned responds, i think it'd make sense to give you commit access.  i'll bring it up in the office tomorrow =)

/cc @dominicbarnes @stevenmiller888

**Comment by zeke** [comment]
Thanks, @stephenmathieson. I was a member of the segmentio github org for a while because I've been maintaining [is-url](https://github.com/segmentio/is-url) but it looks like I've been removed.

**Comment by stephenmathieson** [comment]
looks like you've still got write access to that repo:

<img width="758" alt="screen shot 2016-03-06 at 20 33 52" src="https://cloud.githubusercontent.com/assets/571265/13560939/ca38e76a-e3da-11e5-886b-a25e3c419bf5.png">

if not, ping me and we'll figure it out!

**Comment by MoOx** [comment]
For my concern, following #100, I have now developed for a while [cssnext](http://cssnext.io), a project based on the exact same idea as myth, based on PostCSS instead of Rework. Compared to myth, this project provides now more features, is faster and have probably [less bugs](https://gist.github.com/MoOx/091143e99c6c87fa6d13) (cssnext is now at v2.x, not 0.3 like on the gist).

**Comment by calvinfo** [comment]
Hey @zeke, I've given both you and @ianstormtaylor commit access. Sorry about the oversight! We trust both you guys!

**Comment by zeke** [comment]
Thanks, @calvinfo!

**Comment by madeindonesia** [comment]
@zeke @ianstormtaylor , 
I still think this is great project. Would this be maintained? Since last comming is on Jul 12, 2015

**Comment by zeke** [comment]
I was never really a maintainer of this project, more just a champion of it and a fan of the concepts behind it. I probably won't be making an effort to keep this project alive, but I won't hinder anyone else from doing so either. :)
